project:
  type: book

book:
  title: "Geospatial Data Science with Julia"
  cover-image: "images/cover.svg"
  author: "JÃºlio Hoffimann"
  date: today
  chapters:
    - index.qmd
    - foreword.qmd
    - preface.qmd
    - part: "Part I: Foundations"
      chapters:
        - 01-geodata.qmd
        - 02-geoviz.qmd
        - 03-geoio.qmd
        - 04-geoproc.qmd
    - part: "Part II: Transforms"
      chapters:
        - 05-transforms.qmd
        - 06-projections.qmd
        - 07-pipelines.qmd
    - part: "Part III: Queries"
      chapters:
        - 08-splitcombine.qmd
        - 09-geojoins.qmd
    - part: "Part IV: Interpolation"
      chapters:
        - 10-correlation.qmd
        - 11-interpolation.qmd
    - part: "Part V: Applications"
      chapters:
        - 12-mining.qmd
        - 13-agriculture.qmd
        - 14-energy.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: solar
    mermaid:
      theme: dark